// <auto-generated />
using System;
using Auto_Keep.Models.DbContextAutoKeep;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Auto_Keep.Migrations
{
    [DbContext(typeof(AutoKeepContext))]
    [Migration("20230610155829_InitialAutoKeep")]
    partial class InitialAutoKeep
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Auto_Keep.Models.AutoKeep.EstoqueMonetario", b =>
                {
                    b.Property<int>("Id_Estoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Estoque"));

                    b.Property<string>("DescValor")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Dt_Atualizado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("Moeda")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Nota")
                        .HasColumnType("boolean");

                    b.Property<int?>("Qtd")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Valor_Nota_Moeda")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id_Estoque");

                    b.ToTable("EstoqueMonetarios");
                });

            modelBuilder.Entity("Auto_Keep.Models.AutoKeep.HistoricoVeiculos", b =>
                {
                    b.Property<long>("Id_HistVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id_HistVeiculo"));

                    b.Property<DateTime?>("DataHora_Entrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataHora_Saida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_TiposVeiculos")
                        .HasColumnType("integer");

                    b.Property<bool?>("Pago")
                        .HasColumnType("boolean");

                    b.Property<string>("PlacaVeiculo")
                        .HasColumnType("text");

                    b.Property<decimal?>("Valor_Pago")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Valor_Troco")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id_HistVeiculo");

                    b.HasIndex("Id_TiposVeiculos");

                    b.ToTable("HistoricoVeiculos");
                });

            modelBuilder.Entity("Auto_Keep.Models.AutoKeep.Precos", b =>
                {
                    b.Property<int?>("Id_Preco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id_Preco"));

                    b.Property<int>("Id_TipoVeiculo")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id_Preco");

                    b.HasIndex("Id_TipoVeiculo");

                    b.ToTable("Precos");
                });

            modelBuilder.Entity("Auto_Keep.Models.AutoKeep.TiposVeiculos", b =>
                {
                    b.Property<int>("Id_TipoVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_TipoVeiculo"));

                    b.Property<char?>("Sigla_Veiculo")
                        .HasColumnType("character(1)");

                    b.HasKey("Id_TipoVeiculo");

                    b.ToTable("TiposVeiculos");
                });

            modelBuilder.Entity("Auto_Keep.Models.AutoKeep.HistoricoVeiculos", b =>
                {
                    b.HasOne("Auto_Keep.Models.AutoKeep.TiposVeiculos", "TiposVeiculos")
                        .WithMany()
                        .HasForeignKey("Id_TiposVeiculos");

                    b.Navigation("TiposVeiculos");
                });

            modelBuilder.Entity("Auto_Keep.Models.AutoKeep.Precos", b =>
                {
                    b.HasOne("Auto_Keep.Models.AutoKeep.TiposVeiculos", "TiposVeiculos")
                        .WithMany("Precos")
                        .HasForeignKey("Id_TipoVeiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TiposVeiculos");
                });

            modelBuilder.Entity("Auto_Keep.Models.AutoKeep.TiposVeiculos", b =>
                {
                    b.Navigation("Precos");
                });
#pragma warning restore 612, 618
        }
    }
}
